#ifndef __KERNEL_EMULATIONKIT_POKEMINILIB_EXPORT_GSPOKEMINIAPI_H__
#define __KERNEL_EMULATIONKIT_POKEMINILIB_EXPORT_GSPOKEMINIAPI_H__

#include "IGsPmSystem.h"

GS_API GS_HANDLE GsCreatePokeMiniEmuHandle();

GS_API GS_VOID GsReleasePokeMiniEmuHandle(GS_HANDLE handle);

#endif // __KERNEL_EMULATIONKIT_POKEMINILIB_EXPORT_GSPOKEMINIAPI_H__
